name: "Verify PR"

on:
  pull_request:
    branches:
    - main

jobs:

  docs-build-for-pr:
    uses: recrwplay/actions-demo/.github/workflows/docs-build.yml@main
    with:
      deploy-id: ${{ github.event.number }}

  docs-verify-for-pr:
    needs: docs-build-for-pr
    uses: recrwplay/actions-demo/.github/workflows/docs-verify.yml@main