name: Generate HTML

on:
  workflow_call:
    inputs:
      deploy-id:
        description: 'The PR number if workflow called by a PR'
        required: true
        type: string
        default: 'na'
  workflow_dispatch:
    inputs:
      deploy-id:
        description: 'An id if the output is to be deployed'
        required: true
        type: string
        default: 'id-'


jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm install --production
    - run: npm run build-verify

    - name: Save event-id
      run: echo ${{ inputs.deploy-id }} > ./build/deployid

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: build/
        retention-days: 1          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v2
      with:
        name: antora-log
        path: build/log
        retention-days: 1
