name: "Documentation Teardown"

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
    inputs:
      deploy-uri:
        description: 'The site to teardown'
        required: true
        type: string
        default: ${{ github.event.pull_request.repo.owner.login }}-${{ github.event.pull_request.repo.name }}-${{ github.event.pull_request.number }}.surge.sh
  workflow_call:
    inputs:
      deploy-uri:
        description: 'The site to teardown'
        required: true
        type: string


jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Teardown documentation
        run: |
          npm install -g surge
          surge teardown ${{ github.event.inputs.deploy-uri }} --token ${{ secrets.SURGE_TOKEN }}
          