name: "Verify PR"

on:
  pull_request:
    branches:
    - main

jobs:

  docs-build-for-pr:
    uses: recrwplay/actions-demo/.github/workflows/docs-build.yml@main

  docs-surge:
    needs: docs-build-for-pr
    runs-on: ubuntu-latest

    steps:
    - name: Download HTML
      uses: actions/download-artifact@v2
      with:
        name: docs

    - name: List files
      run: ls -R
      working-directory: site
    
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Deploy documentation to surge
      run: |
        npm install -g surge
        surge ./site recrwplay-actions-demo-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

  docs-verify-for-pr:
    needs: docs-build-for-pr
    uses: recrwplay/actions-demo/.github/workflows/docs-verify.yml@main