# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Verify PR"

on:
  pull_request:
    branches:
    - dev

jobs:

  docs-build-for-pr:
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-build.yml@dev
    with:
      deploy-id: ${{ github.event.number }}
      retain-artifacts: 14
      pageList: true

  docs-verify-for-pr:
    needs: docs-build-for-pr
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-verify.yml@dev

  docs-deploy-links-for-pr:
    if: ${{ needs.docs-build-for-pr.outputs.pages-listed == 'success' }}
    needs: docs-build-for-pr
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-pr-changes.yml@dev

  docs-lint-for-pr:
    needs: docs-pr-deploy-links
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-lint.yml@dev
    with:
      files: ${{ needs.docs-deploy-links-for-pr.outputs.asciidoc-files }}
      vale-fail-on-error: true
      reporter: github-pr-check
      separator: ','


