name: Generate HTML

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm install --production
    - run: npm run build-verify

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: build/
        retention-days: 1          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v2
      with:
        name: antora-log
        path: build/log
        retention-days: 1
