# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Verify Branch"

on:
  push:
    branches:
    - dev
  schedule:
    - cron:  '00 16 * * *'

jobs:

  docs-build:
    name: Generate HTML
    uses: neo4j/.github/workflows/reusable-docs-build.yml@v1.1.0
    with:
      retain-artifacts: 14
      deploy-id: 0

  docs-verify:
    name: Verify HTML
    needs: docs-build
    uses: neo4j/actions-demo/.github/workflows/reusable-docs-verify.yml@v1.1.0

  docs-links:
    name: Check links
    needs: docs-build
    uses: neo4j/actions-demo/.github/workflows/reusable-docs-links.yml@v1.1.0

  docs-lint:
    name: Lint docs
    uses: neo4j/actions-demo/.github/workflows/reusable-docs-lint.yml@v1.1.0