# Documentation Style Guide Lint
# Uses Vale to lint documentation against the Documentation Style Guide
# Current POC uses the Google style guide as a base set of rules
# See .vale.ini for the current set of rules

name: "Documentation Style Guide Check"

on:
  workflow_call:
    inputs:
      files:
        description: 'The files to lint'
        default: '["modules/ROOT/pages", "modules/ROOT/partials"]'
        type: string
      vale-fail-on-error:
        description: 'Report vale errors as a failure'
        default: false
        type: boolean
      reporter:
        description: 'Where action messages are reported'
        type: string
        default: 'github-check'
      separator:
        description: 'Delimiter for input files or folders'
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      files:
        description: 'The files to lint'
        default: '["modules/ROOT/pages", "modules/ROOT/partials"]'
        type: string
      vale-fail-on-error:
        description: 'Report vale errors as a failure'
        default: false
        type: boolean
      reporter:
        description: 'Where action messages are reported'
        type: string
        default: 'github-check'
      separator:
        description: 'Delimiter for input files or folders'
        type: string
        default: ''

jobs:

  lint:
    name: Lint with Vale
    runs-on: ubuntu-latest
    if: ${{ inputs.files != '[]' }}
    steps:
      - uses: actions/checkout@v3

      - name: download rules
        uses: actions/checkout@v3
        with:
          repository: recrwplay/antora-build-verify
          ref: dev
          path: vale-rules
          sparse-checkout: |
            styles
          sparse-checkout-cone-mode: false

      - name: list files
        run: ls -R

      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ inputs.files }}
          reporter: ${{ inputs.reporter }}
          fail_on_error: ${{ inputs.vale-fail-on-error }}
          separator: ${{ inputs.separator }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
