name: Generate HTML

on:
  workflow_call:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        type: string
        default: 'build-verify'
      deploy-id:
        description: 'The PR number if workflow called by a PR'
        required: true
        type: string
        default: 'na'
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        required: true
        type: number
        default: 7
  workflow_dispatch:
    inputs:
      package-script:
        description: 'The name of the script to run in package.json '
        required: true
        type: string
        default: 'build-verify'
      deploy-id:
        description: 'An id if the output is to be deployed'
        required: true
        type: string
        default: 'id-'
      retain-artifacts:
        description: 'The number of days to retain artifacts'
        required: true
        type: number
        default: 7


jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - run: npm install --omit=dev
    - run: npm run ${{ inputs.package-script }}

    - name: Save event-id
      run: echo ${{ inputs.deploy-id }} > ./build/deployid

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: build/
        retention-days: ${{ inputs.retain-artifacts }}          

    - name: Upload Log artifact
      uses: actions/upload-artifact@v3
      with:
        name: antora-log
        path: build/log
        retention-days: ${{ inputs.retain-artifacts }}
