name: Verify HTML

on:
  workflow_call:
    inputs:
      failOnErrors:
        description: 'Fail on log errors (boolean)'
        default: true
        type: boolean

jobs:
  log-report:
    runs-on: ubuntu-latest

    steps:

    - name: Download Antora log
      uses: actions/download-artifact@v2
      with:
        name: antora-log

    - name: Analyze Antora log
      id: antora-log-check-test
      uses: recrwplay/antora-log-analyzer@main
      with:
        fail-on-errors: ${{ inputs.failOnErrors }}
