# Use this starter workflow in your repo to publish a development or production AWS S3 bucket
# By default it runs against the default branch and assumes the default branch publishes to production S3

name: "Publish HTML"

on:
  workflow_dispatch:
  push:
    branches:
    - dev
    - master

jobs:

  docs-ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.ref.outputs.ref }}
    steps:
    - id: branch-name
      name: Get branch name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

  docs-build-for-publish:
    needs: docs-ref
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-build.yml@main
    with:
      deploy-id: ${{ needs.docs-ref.outputs.branch }}
      retain-artifacts: 7

  docs-verify-for-publish:
    needs: docs-build-for-publish
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-verify.yml@main

  docs-publish-dev:
    needs: docs-verify-for-publish
    if: ${{ needs.docs-ref.outputs.branch == 'dev' }}
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-publish.yml@main
    with:
      docs-artifact: docs
      source-dir: site/
      extra-args: --dryrun
    secrets:
      aws-s3-bucket: ${{ secrets.DEVELOPMENT_AWS_CONFIG_BUCKET }}
      aws-s3-id: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
      aws-s3-secret: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
      aws-s3-region: ${{ secrets.DEVELOPMENT_AWS_REGION }}

  docs-publish-prod:
    needs: docs-verify-for-publish
    if: ${{ needs.docs-ref.outputs.branch != 'master' }}
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-publish.yml@main
    with:
      docs-artifact: docs
      source-dir: site/
      extra-args: --dryrun
    secrets:
      aws-s3-bucket: ${{ secrets.PRODUCTION_AWS_CONFIG_BUCKET }}
      aws-s3-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
      aws-s3-secret: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
      aws-s3-region: ${{ secrets.PRODUCTION_AWS_REGION }}