# This is an example of the docs-publish-dev-prod.yml workflow available from the recrwplay org
name: "Publish HTML"

on:
  workflow_dispatch:
  push:
    branches:
    - dev

jobs:

  docs-get-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.branch }}
    steps:
    - id: branch-name
      name: Get branch name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

  docs-build-for-publish:
    needs: docs-get-branch
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-build.yml@main
    with:
      deploy-id: ${{ needs.docs-get-branch.outputs.branch }}
      retain-artifacts: 28

  docs-verify-for-publish:
    needs: docs-build-for-publish
    uses: recrwplay/actions-demo/.github/workflows/reusable-docs-verify.yml@main

  docs-publish-dev:
    needs: docs-verify-for-publish
    if: ${{ needs.docs-get-branch.outputs.branch != 'dev' }}
    runs-on: ubuntu-latest
    steps:
    - name: Sync to development
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --dryrun
      env:
        AWS_S3_BUCKET: ${{ secrets.DEVELOPMENT_AWS_CONFIG_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
        AWS_S3_SECRET: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
        AWS_S3_REGION: ${{ secrets.DEVELOPMENT_AWS_REGION }}

  docs-publish-prod:
    needs: docs-verify-for-publish
    if: ${{ needs.docs-get-branch.outputs.branch == 'dev' }}
    runs-on: ubuntu-latest
    steps:
    - name: Sync to production
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --dryrun
      env:
        AWS_S3_BUCKET: ${{ secrets.PRODUCTION_AWS_CONFIG_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
        AWS_S3_SECRET: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
        AWS_S3_REGION: ${{ secrets.PRODUCTION_AWS_REGION }}